### PR TITLE
Add metadata file with event additions order  #25

### PR DESCRIPTION
**Pull request by Daniel-at-github**
Generated using the instructions in:
https://github.com/pyvideo/pyvideo/issues/25#issuecomment-263054676

### CODE REVIEW

**Comment by zerok** [comment]
Shouldn't this file be generated by the build system if it's even needed?

**Comment by logston** [comment]
Can we create a plugin that runs a subprocess to get this info and order the rss feed? Great work by the way @Daniel-at-github

**Comment by Daniel-at-github** [comment]
Automating it's better than maintaining the file manually. Getting the info and ordering it should be easy. Using it in a plugin, I don't know how to start.

**Comment by Daniel-at-github** [comment]
Done in #32

**Pull request closed without merging**
