### PR TITLE
Sort RSS/Atom feeds based on event merge date

### LINKED ISSUE #25: paginate through latest talks?
i've been using pyvideo quite a bit over the last few days and sometimes I'm just looking to watch something new that catches my eye as opposed to going to a particular conference or tag or speaker. would love to be be able to just paginate through some of the most recent videos

### PR DESCRIPTION
**Pull request by logston**
Closes #25

### CODE REVIEW

**Comment by logston** [comment]
@Daniel-at-github Can I get your review of this plugin? It uses your shell script for listing sorted event directories.

**Comment by Daniel-at-github** [comment]
In Python 3.4.3 fails with:
~~~
CRITICAL: AttributeError: 'module' object has no attribute 'run'
Traceback (most recent call last):
  File "/home/user/.virtualenvs/pytube/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/user/.virtualenvs/pytube/lib/python3.4/site-packages/pelican/__init__.py", line 478, in main
    pelican.run()
  File "/home/user/.virtualenvs/pytube/lib/python3.4/site-packages/pelican/__init__.py", line 183, in run
    p.generate_output(writer)
  File "/home/user/.virtualenvs/pytube/lib/python3.4/site-packages/pelican/generators.py", line 586, in generate_output
    self.generate_feeds(writer)
  File "/home/user/.virtualenvs/pytube/lib/python3.4/site-packages/pelican/generators.py", line 294, in generate_feeds
    self.settings['FEED_ALL_ATOM'])
  File "/home/user/git/pytube/plugins/writer.py", line 12, in write_feed
    elements = self.sort_elements(elements)
  File "/home/user/git/pytube/plugins/writer.py", line 16, in sort_elements
    return sorted(elements, key=self.key_func)
  File "/home/user/git/pytube/plugins/writer.py", line 21, in key_func
    cmp_key = self.sorted_events.index(event_dir)
  File "/home/user/git/pytube/plugins/writer.py", line 27, in sorted_events
    output = subprocess.run(["./sort_events.sh"], stdout=subprocess.PIPE)
AttributeError: 'module' object has no attribute 'run'
~~~
Have to try it in Python 3.5

**Comment by Daniel-at-github** [comment]
It works, but I can´t merge it (no commit permission). 
My revision is a PR (#34) to translate it to python.

**Comment by logston** [comment]
Thanks @Daniel-at-github !

**Pull request merged**
