### PR TITLE
Fast-forward data dir 2016-12-12

### PR DESCRIPTION
**Pull request by redapple**
Is this the way to go for updating the main website?

### CODE REVIEW

**Comment by redapple** [comment]
> Is this the way to go for updating the main website?

Travis failing: I guess not :)

**Comment by zerok** [comment]
@redapple It previously was, but Travis changed its openssl setup, which is fighting us ever since :( I'm very much tempted to just build a cronjob on my own machine ;)

**Comment by redapple** [comment]
Oh.
@zerok , so what's the current way to get around this?
Is it done manually by one of the website maintainers?

**Comment by zerok** [comment]
@logston You did that manually the last time, right?

**Comment by logston** [comment]
Yeah, I have to update this. But @lgh2 usually jumps on fast forwards pretty quickly.

**Comment by logston** [comment]
@redapple You should have write access now. Can you rebase and retry?

**Comment by redapple** [comment]
Thanks. On mobile now. I'll try tomorrow if you don't beat me to it

**Pull request closed without merging**
